blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from .feeds import LatestPostsFeed

from core.sitemaps import PostSitemap
from core import views


app_name = 'core'

sitemaps = {
    'posts':PostSitemap,
}

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps }, name='django.contrib.sitemaps.views.sitemap'),
    path('<int:post_id>/share/', views.post_share, name='post_share'), 
    path('search/', views.post_search, name='post_search'),
    path('feed/', LatestPostsFeed(), name='post_feed')
] 

core/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.db import models
#taggit 
from taggit.managers import TaggableManager



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title       =   models.CharField(max_length=250)
    slug        =   models.SlugField(max_length=250, unique_for_date='publish')
    author      =   models.ForeignKey( User, on_delete=models.CASCADE, related_name='blog_post')
    body        =   models.TextField()
    publish     =   models.DateTimeField(default=timezone.now)
    created     =   models.DateTimeField(auto_now_add=True)
    updated     =   models.DateTimeField(auto_now=True)
    status      =   models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects     =   models.Manager() 
    published   =   PublishedManager()

    tags = TaggableManager()

    class meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title 
    
    def get_absolute_url(self):
        return reverse('core:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

core/forms.py
from django import forms
from .models import Comment 



class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

        
class SearchForm(forms.Form):
    query = forms.CharField()

core/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.mail import send_mail
from django.db.models import Count
#Taggit
from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm



def post_list(request, tag_slug=None):
    object_list = Post.published.all().order_by('-created',)
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags=tag.id)
    paginator = Paginator(object_list, 3) #3 post in each page.
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        #If pager is out of range deliver last page of result
        posts = paginator.page(paginator.num_pages)

    return render(request, 'core/post/list.html', {'page':page, 'posts':posts, 'tag':tag})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags',
                                                                             '-publish')[:4]
    return render(request, 'core/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})



def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'core/post/share.html', {'post': post, 'form': form, 'sent': sent})



def post_search(request):
    form = SearchForm()
    query = None 
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)  
            results = Post.objects.annotate(
                                            rank=SearchRank(search_vector, search_query)
                                            ).filter(rank__gte=0.3).order_by('-rank')

    return render(request, 'core/post/search.html', {'form':form, 'query': query, 'results':results})

core/templates/core/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    </head>
    <body>
        <style>.date{color:grey}#sidebar{ color: grey; margin-right: 5px;}
        </style>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3" >
                    <div class="col-8" id="sidebar">
                        <br>
                        <a href="{% url "core:post_list"  %}"><h2>Home</h2></a>
                        <br>
                        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
                        <p><a href="{% url "core:post_feed" %}">Subscribe to my RSS feed</a></p>

                        <h3>Latest posts</h3>
                        {% show_latest_posts 3 %}

                        <h3>Most commented posts</h3>
                        {% get_most_commented_posts as most_commented_posts %}
                        <ul>
                        {% for post in most_commented_posts %}
                            <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
                        {% endfor %}
                        </ul>
                        <br>
                        <p><a href="{% url "core:post_search" %}">Search matches</a></p>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="col-11">
                        <div id="content">
                            {% block content %}
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

core/templates/core/pagination.html
<div class="pagination">
	<span class="step-links">
			{% if page.has_previous %}
					<a href="?page={{ page.previous_page_number }}">Previous</a>
			{% endif %}
			<span class="current">
					Page {{ page.number }} of {{ page.paginator.num_pages }}
			</span>
				{% if page.has_next %}
					<a href="?page={{ page.next_page_number }}">Next</a>
				{% endif %}
	</span>
</div>

core/templates/core/post/comment.html
{% extends "blog/base.html" %}

{% block title %}New comment{% endblock %}

{% block content %}
    <h2>New comment for post "{{ post.title }}"</h2>
    <form action="." method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add comment">
    </form>
{% endblock %}

core/templates/core/post/detail.html
{% extends 'core/base.html' %}

{% block title %}{{post.title}}{% endblock%}

{% block content %}
    <br>
    <h2>{{post.title}}</h2>
    <hr>
    <p class="date">
        Published {{post.publish}} by {{post.author}}
    </p>
        {{post.body|linebreaks}}
    <p>
        <a href="{% url 'core:post_share' post.id %}">
            share this post
        </a>
    </p>
    <h4>Similar posts</h4>
        {% for post in similar_posts %}
            <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
        {% empty %}
            There are no similar posts yet.
        {% endfor %}
    <hr>
    {% with comments.count as total_comments %}
        <h4>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h4>
    {% endwith %}
    {% for comment in comments %}
    <div class="comment">
        <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
        {{ comment.body|linebreaks }}
    </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
        <h4>Your comment has been added.</h4>
    {% else %}
        <h4>Add a new comment</h4>
        <form action="." method="post">
            <div class="form-control form-control-lg" placeholder=".form-control-lg">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
            </div>
        </form>
    {%  endif %}
{% endblock %}

core/templates/core/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
    </ul>

core/templates/core/post/list.html
{% extends 'core/base.html' %}

{% block title %}Articles blog{% endblock%}

{% block content %}
        <br>
        <h2>Articles blog</h2>
        <hr>
        {% if tag %}
            <h4>Post tagged with "{{ tag.name }}"</h4>
        {% endif %}
        {% for post in posts %}
        <h4><a href=" {{ post.get_absolute_url}} ">{{post.slug|title}}</a></h4>
        <br>
        {{post.body|truncatewords:30|linebreaks}}
            <p class="date">
                Published in {{ post.publish }} by {{ post.author }}
            </p>
        <p class="tags">
        {% if post.tags.all|length > 0 %}
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "core:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        {% endif %}
        </p>
        <hr>
        {% endfor %}
        <br>
        {% include 'core/pagination.html' with page=posts %}
{% endblock%}

core/templates/core/post/search.html
{% extends "core/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if "query" in request.GET %}
        <br>
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">
            <br>
            {{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <br>
        	<p>There are no results for your query.</p>
        {% endfor %}
        <p><br><a href="{% url "core:post_search" %}">Search again</a></p>
    {% else %}
        <br>
        <h1>Search for posts</h1>
        <br>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

core/templates/core/post/share.html
{% extends 'core/base.html' %}

{% block title %} Share a post {% endblock%}

{% block content %}  
    {% if sent %}
        <h1>E-mail succesfully sent </h1>
        <p>
            "{{post.title}} was succesfully sent to {{ form.cleaned_data.to }}"
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail </h1>
        <form action="." method="post">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock%}